services:
  - type: web
    name: my-playwright-service
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: PORT
        value: 4000  # Or any port you prefer
